version: 3
workflow_filters: &workflow_filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy_doc: *workflow_filters
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cache_and_run_tests
