name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install -r requirements_dev.txt
        pip install -e .
    - name: Run tests
      run: |
        pytest tests/test_question_answering.py
        pytest tests/test_sequence_classifier.py
        pytest tests/test_summarizer.py
        pytest tests/test_text_generation.py
        pytest tests/test_token_tagger.py
        pytest tests/test_trained_embeddings.py
        pytest tests/test_translator.py
